// src/content/config.ts
//
// This is the "real blog" requested to replace the old client-side RSS
// widget that had no per-post URLs and wasn't indexable. Posts are plain
// Markdown files under src/content/blog/, compiled to static HTML at build
// time like every other page — same zero-runtime-JS guarantee as the rest
// of the site.
//
// scripts/generate-daily-brief.mjs is the automated writer. The GitHub
// Actions workflow .github/workflows/daily-brief.yml runs it every morning
// and commits the new Markdown file to this repo; Vercel rebuilds on the
// push. No CMS, database, or Vercel cron is involved.

import { defineCollection, z } from "astro:content";

const blog = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string(),
    description: z.string().max(200),
    publishDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    author: z.string().default("CloudGrid Africa Engineering"),
    category: z.enum(["security", "cloud", "compliance", "engineering", "industry"]),
    tags: z.array(z.string()).default([]),
    /** true for posts written by the daily automation pipeline */
    autoGenerated: z.boolean().default(false),
    heroImage: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { blog };
