// src/content/config.ts
//
// This is the "real blog" requested to replace the old client-side RSS
// widget that had no per-post URLs and wasn't indexable. Posts are plain
// Markdown files under src/content/blog/, compiled to static HTML at build
// time like every other page — same zero-runtime-JS guarantee as the rest
// of the site.
//
// netlify/functions/generate-daily-post.js is the automated writer: a
// Netlify Scheduled Function that runs once daily, curates Kenya/Africa/
// world tech coverage, and commits a new Markdown file matching this exact
// schema directly to the connected GitHub repository — which triggers
// Netlify's normal auto-deploy and regenerates these pages with the new
// post included. No custom CMS or database is required.

import { defineCollection, z } from "astro:content";

const blog = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string(),
    description: z.string().max(200),
    publishDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    author: z.string().default("CloudGrid Africa Engineering"),
    category: z.enum(["security", "cloud", "compliance", "engineering", "industry"]),
    tags: z.array(z.string()).default([]),
    /** true for posts written by the daily automation pipeline */
    autoGenerated: z.boolean().default(false),
    heroImage: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { blog };
