// scripts/lib/daily-brief.mjs
//
// Shared helpers for the daily brief: text clean-up and the Markdown format
// written to src/content/blog/daily-brief-YYYY-MM-DD.md (schema in
// src/content/config.ts). Used by scripts/generate-daily-brief.mjs, which
// the GitHub Actions workflow runs every morning.

const NAMED = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ", hellip: "…",
  mdash: "—", ndash: "–", lsquo: "‘", rsquo: "’", ldquo: "“", rdquo: "”" };

// Feeds are often double-encoded ("&amp;#8217;"), so decode until stable.
export function decodeEntities(input = "") {
  let s = input;
  for (let i = 0; i < 3; i++) {
    const next = s
      .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
      .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
      .replace(/&([a-z]+);/gi, (m, n) => NAMED[n.toLowerCase()] ?? m);
    if (next === s) break;
    s = next;
  }
  return s;
}

export function cleanText(input = "") {
  return decodeEntities(input.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1").replace(/<[^>]+>/g, " "))
    .replace(/[\p{Extended_Pictographic}\uFE0F\u200D]/gu, "") // feed titles sometimes carry emoji
    .replace(/\s+/g, " ")
    .trim();
}

// One or two sentences, never a fragment like "A U.S." (the old pipeline
// split on the first full stop, abbreviations included).
export function summarize(desc = "") {
  const text = cleanText(desc).replace(/\s*\[…\]$|\s*\[\.\.\.\]$|\s*The post .* appeared first on .*$/i, "");
  if (text.length < 40) return "";
  if (text.length <= 240) return text;
  const cut = text.slice(0, 240);
  const lastStop = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("? "), cut.lastIndexOf("! "));
  if (lastStop >= 80) return cut.slice(0, lastStop + 1);
  return cut.slice(0, cut.lastIndexOf(" ")) + "…";
}

const esc = (s) => s.replace(/"/g, '\\"');
const md = (s) => s.replace(/([\\*_`\[\]<>])/g, "\\$1");

export function renderBrief({ date, stories }) {
  const human = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" })
    .format(new Date(`${date}T00:00:00Z`));
  let description = stories.map((s) => s.title).join("; ");
  if (description.length > 195) description = description.slice(0, 194).replace(/\s+\S*$/, "") + "…";

  const front = [
    "---",
    `title: "Daily brief — ${human}"`,
    `description: "${esc(description)}"`,
    `publishDate: ${date}`,
    `author: "CloudGrid Africa"`,
    `category: "industry"`,
    `tags: ["Daily brief", ${[...new Set(stories.map((s) => `"${esc(s.lane)}"`))].join(", ")}]`,
    `autoGenerated: true`,
    `draft: false`,
    "---",
  ].join("\n");

  const body = stories
    .map((s) => {
      const parts = [`## ${md(s.title)}`, ""];
      if (s.summary) parts.push(md(s.summary), "");
      parts.push(`${s.lane}. Source: [${md(s.source)}](${s.link})`);
      return parts.join("\n");
    })
    .join("\n\n");

  return `${front}

Three stories from security, cloud and East African tech sources, picked automatically each morning. Summaries are the publishers' own excerpts; follow the source link for the full story.

${body}
`;
}
